"""DOCX (and optional PDF) export for HIPAA assessment and roadmap reports."""
from __future__ import annotations

import io
import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone

from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Inches, Pt, RGBColor

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    _MPL_OK = True
except Exception:
    _MPL_OK = False


DARK = "1A1A2E"
ACCENT = "2D6A9F"
GRAY = "444444"
LGRAY = "777777"
FONT = "Calibri"

DISCLAIMER_TEXT = (
    "This report is generated by an automated readiness tool. "
    "This document does not constitute legal advice or a formal HIPAA audit. "
    "Organizations should engage a qualified HIPAA compliance professional to "
    "validate findings and develop a formal compliance program."
)


def _hex_to_rgb(hex_str: str) -> RGBColor:
    return RGBColor(int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16))


def _set_default_font(doc: Document) -> None:
    style = doc.styles["Normal"]
    style.font.name = FONT
    style.font.size = Pt(11)
    rpr = style.element.get_or_add_rPr()
    rfonts = rpr.find(qn("w:rFonts"))
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.append(rfonts)
    rfonts.set(qn("w:ascii"), FONT)
    rfonts.set(qn("w:hAnsi"), FONT)
    rfonts.set(qn("w:cs"), FONT)
    for level in ("Heading 1", "Heading 2", "Heading 3"):
        try:
            hs = doc.styles[level]
            hs.font.name = FONT
            hrpr = hs.element.get_or_add_rPr()
            hrf = hrpr.find(qn("w:rFonts"))
            if hrf is None:
                hrf = OxmlElement("w:rFonts")
                hrpr.append(hrf)
            hrf.set(qn("w:ascii"), FONT)
            hrf.set(qn("w:hAnsi"), FONT)
            hrf.set(qn("w:cs"), FONT)
        except KeyError:
            continue


def _add_heading(doc: Document, text: str, level: int = 1, color_hex: str = ACCENT) -> None:
    h = doc.add_heading(level=level)
    run = h.add_run(text)
    run.font.name = FONT
    run.font.color.rgb = _hex_to_rgb(color_hex)
    if level == 1:
        run.font.size = Pt(20)
    elif level == 2:
        run.font.size = Pt(14)
    else:
        run.font.size = Pt(12)
    run.bold = True


def _add_para(doc: Document, text: str, size: int = 11, color_hex: str = GRAY,
              bold: bool = False, align: int | None = None) -> None:
    p = doc.add_paragraph()
    if align is not None:
        p.alignment = align
    run = p.add_run(text)
    run.font.name = FONT
    run.font.size = Pt(size)
    run.font.color.rgb = _hex_to_rgb(color_hex)
    run.bold = bold


def _shade_cell(cell, hex_color: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)


def _style_header_cell(cell) -> None:
    _shade_cell(cell, ACCENT)
    for p in cell.paragraphs:
        for run in p.runs:
            run.font.name = FONT
            run.font.bold = True
            run.font.size = Pt(10)
            run.font.color.rgb = _hex_to_rgb("FFFFFF")
    cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER


def _style_body_cell(cell, size: int = 10, color_hex: str = GRAY) -> None:
    for p in cell.paragraphs:
        for run in p.runs:
            run.font.name = FONT
            run.font.size = Pt(size)
            run.font.color.rgb = _hex_to_rgb(color_hex)
    cell.vertical_alignment = WD_ALIGN_VERTICAL.TOP


def _build_table(doc: Document, headers: list[str], rows: list[list[str]],
                 col_widths: list[float] | None = None) -> None:
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr[i].text = h
        _style_header_cell(hdr[i])
    for r_idx, row in enumerate(rows, start=1):
        cells = table.rows[r_idx].cells
        for c_idx, val in enumerate(row):
            cells[c_idx].text = "" if val is None else str(val)
            _style_body_cell(cells[c_idx])
    if col_widths:
        for row in table.rows:
            for i, w in enumerate(col_widths):
                if i < len(row.cells):
                    row.cells[i].width = Inches(w)


def _render_score_chart(category_scores: dict) -> bytes | None:
    if not _MPL_OK:
        return None
    try:
        cats = ["Administrative", "Physical", "Technical", "Privacy", "Breach Notification"]
        vals = [float(category_scores.get(c, 0) or 0) for c in cats]
        labels = ["Administrative", "Physical", "Technical", "Privacy", "Breach\nNotification"]

        fig, ax = plt.subplots(figsize=(8, 4))
        bars = ax.bar(labels, vals, color="#" + ACCENT, edgecolor="#" + DARK)
        ax.set_ylim(0, 100)
        ax.set_ylabel("Readiness %", color="#" + DARK)
        ax.set_title("Readiness Score by Safeguard Category", color="#" + DARK, fontsize=13, pad=12)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(colors="#" + GRAY)
        ax.yaxis.label.set_color("#" + DARK)
        ax.axhline(75, color="#" + LGRAY, linestyle=":", linewidth=0.8)
        for bar, v in zip(bars, vals):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 1.5,
                f"{v:.0f}%",
                ha="center", va="bottom", fontsize=9, color="#" + DARK,
            )
        fig.tight_layout()
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=160, bbox_inches="tight")
        plt.close(fig)
        return buf.getvalue()
    except Exception:
        return None


def _utc_today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _band_for_score(score: float) -> tuple[str, str]:
    if score >= 90:
        return "Audit Ready", "#22C55E"
    if score >= 75:
        return "Strong", "#84CC16"
    if score >= 50:
        return "Partial", "#EAB308"
    return "Critical", "#DC2626"


def generate_assessment_docx(
    org_context: dict,
    readiness: dict,
    controls: list[dict],
    baa_summary: dict,
    claude_analysis: dict | None = None,
) -> bytes:
    doc = Document()
    _set_default_font(doc)

    org_name = org_context.get("org_name", "Organization")
    score = float(readiness.get("overall", 0) or 0)
    band = readiness.get("band_label") or _band_for_score(score)[0]
    today = _utc_today()

    _add_para(doc, "HIPAA READINESS ASSESSMENT", size=12, color_hex=ACCENT,
              bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, org_name, size=28, color_hex=DARK, bold=True,
              align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, f"Assessment Date (UTC): {today}", size=11, color_hex=LGRAY,
              align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, f"Overall Score: {score:.1f}%  ·  {band}", size=14, color_hex=DARK,
              bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, f"Entity Type: {org_context.get('entity_type', 'N/A')}", size=11,
              color_hex=GRAY, align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, f"Prepared by: HIPAA Readiness Agent", size=10, color_hex=LGRAY,
              align=WD_ALIGN_PARAGRAPH.CENTER)

    doc.add_page_break()

    _add_heading(doc, "Executive Summary", level=1)
    if claude_analysis and claude_analysis.get("gap_summary"):
        _add_para(doc, claude_analysis.get("gap_summary", ""), size=11, color_hex=GRAY)
        risk_tier = claude_analysis.get("overall_risk_tier")
        if risk_tier:
            _add_para(doc, f"Overall Risk Tier: {risk_tier}", size=11,
                      color_hex=DARK, bold=True)
        if claude_analysis.get("audit_exposure"):
            _add_para(doc, "Auditor exposure: " + claude_analysis["audit_exposure"],
                      size=11, color_hex=GRAY)
    else:
        implemented = readiness.get("implemented_count", 0)
        total = readiness.get("total_controls", 0)
        _add_para(
            doc,
            f"{org_name} scored {score:.1f}% across the HIPAA Security Rule control set, "
            f"placing the program in the {band} readiness band.",
            size=11, color_hex=GRAY,
        )
        _add_para(
            doc,
            f"Of {total} controls evaluated, {implemented} are fully implemented. "
            f"Critical and high gaps are detailed in the tables that follow, with recommended "
            f"actions tied directly to the underlying CFR citation.",
            size=11, color_hex=GRAY,
        )

    _add_heading(doc, "Score by Safeguard Category", level=2)
    chart_png = _render_score_chart(readiness.get("category_scores", {}) or {})
    if chart_png:
        doc.add_picture(io.BytesIO(chart_png), width=Inches(6))
    else:
        _add_para(doc, "Chart unavailable (matplotlib not installed in this environment).",
                  size=10, color_hex=LGRAY)
        cat_scores = readiness.get("category_scores", {}) or {}
        rows = [[c, f"{float(cat_scores.get(c, 0) or 0):.1f}%"]
                for c in ["Administrative", "Physical", "Technical", "Privacy", "Breach Notification"]]
        _build_table(doc, ["Category", "Score"], rows, col_widths=[3.5, 2.0])

    ctrl_map = {c["id"]: c for c in controls}

    def _gap_rows(gaps: list[dict]) -> list[list[str]]:
        rows = []
        for g in gaps or []:
            cid = g.get("control_id", "")
            c = ctrl_map.get(cid, {}) or {}
            citation = c.get("cfr_citation", "")
            status = g.get("status", "")
            action = g.get("immediate_action") or g.get("recommended_action") or g.get("notes") or c.get("spec", "")
            rows.append([cid, citation, status, action])
        return rows

    critical = readiness.get("critical_gaps", []) or []
    _add_heading(doc, f"Critical Gaps ({len(critical)})", level=2, color_hex="DC2626")
    if critical:
        _build_table(
            doc,
            ["Control", "CFR Citation", "Status", "Recommended Action"],
            _gap_rows(critical),
            col_widths=[1.0, 1.6, 1.2, 2.7],
        )
    else:
        _add_para(doc, "No critical gaps identified.", size=11, color_hex=GRAY)

    high = readiness.get("high_gaps", []) or []
    _add_heading(doc, f"High Gaps ({len(high)})", level=2, color_hex="F97316")
    if high:
        _build_table(
            doc,
            ["Control", "CFR Citation", "Status", "Recommended Action"],
            _gap_rows(high),
            col_widths=[1.0, 1.6, 1.2, 2.7],
        )
    else:
        _add_para(doc, "No high gaps identified.", size=11, color_hex=GRAY)

    _add_heading(doc, "Business Associate Agreement Summary", level=2)
    baa_rows = [
        ["Total BAAs", str(baa_summary.get("total", 0))],
        ["Missing BAAs", str(baa_summary.get("missing_baas", 0))],
        ["Expired BAAs", str(baa_summary.get("expired", 0))],
        ["Expiring within 90 days", str(baa_summary.get("expiring_90d", 0))],
        ["ePHI-sharing Vendors", str(baa_summary.get("ephi_vendors", 0))],
    ]
    if "critical" in baa_summary or "high" in baa_summary:
        baa_rows.append(["Critical Risk Tier", str(baa_summary.get("critical", 0))])
        baa_rows.append(["High Risk Tier", str(baa_summary.get("high", 0))])
    _build_table(doc, ["Metric", "Count"], baa_rows, col_widths=[3.5, 2.0])

    doc.add_paragraph()
    _add_heading(doc, "Disclaimer", level=2, color_hex=LGRAY)
    _add_para(doc, DISCLAIMER_TEXT, size=10, color_hex=LGRAY)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def generate_roadmap_docx(
    org_context: dict,
    roadmap: dict,
    controls: list[dict],
    refine_meta: dict | None = None,
) -> bytes:
    doc = Document()
    _set_default_font(doc)

    org_name = org_context.get("org_name", "Organization")
    today = _utc_today()
    summary = roadmap.get("executive_summary", "") or ""
    risk_tier = roadmap.get("overall_risk_tier", "") or ""

    _add_para(doc, "HIPAA REMEDIATION ROADMAP", size=12, color_hex=ACCENT,
              bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, org_name, size=28, color_hex=DARK, bold=True,
              align=WD_ALIGN_PARAGRAPH.CENTER)
    _add_para(doc, f"Generated (UTC): {today}", size=11, color_hex=LGRAY,
              align=WD_ALIGN_PARAGRAPH.CENTER)
    if risk_tier:
        _add_para(doc, f"Overall Risk Tier: {risk_tier}", size=14, color_hex=DARK,
                  bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)

    doc.add_paragraph()
    _add_heading(doc, "Executive Summary", level=1)
    if summary:
        _add_para(doc, summary, size=11, color_hex=GRAY)
    else:
        _add_para(
            doc,
            "Phased remediation plan covering Phase 1 critical fixes, Phase 2 policy and "
            "documentation work, and Phase 3 audit readiness.",
            size=11, color_hex=GRAY,
        )

    doc.add_page_break()

    ctrl_map = {c["id"]: c for c in controls}
    headers = ["Control / CFR", "Title", "Owner", "Effort", "Priority", "Expected Artifact"]
    col_widths = [1.6, 2.0, 1.0, 0.7, 0.7, 1.5]

    phases = roadmap.get("phases", []) or []
    for phase in phases:
        phase_num = phase.get("phase", "?")
        label = phase.get("label") or f"Phase {phase_num}"
        items = phase.get("items", []) or []
        _add_heading(doc, f"Phase {phase_num}: {label}", level=2)
        if phase.get("description"):
            _add_para(doc, phase["description"], size=11, color_hex=GRAY)
        if not items:
            _add_para(doc, "No actions in this phase.", size=10, color_hex=LGRAY)
            continue

        rows = []
        for item in items:
            cid = item.get("control_id", "")
            c = ctrl_map.get(cid, {}) or {}
            citation = c.get("cfr_citation", "")
            ref = f"{cid}\n{citation}" if citation else cid
            rows.append([
                ref,
                item.get("title", ""),
                item.get("owner_role", ""),
                item.get("effort", ""),
                item.get("priority", ""),
                item.get("expected_artifact", ""),
            ])
        _build_table(doc, headers, rows, col_widths=col_widths)
        doc.add_paragraph()

    quick_wins = roadmap.get("quick_wins", []) or []
    _add_heading(doc, f"Quick Wins ({len(quick_wins)})", level=2, color_hex="22C55E")
    if quick_wins:
        qw_rows = []
        for w in quick_wins:
            cid = w.get("control_id", "")
            c = ctrl_map.get(cid, {}) or {}
            citation = c.get("cfr_citation", "")
            ref = f"{cid}  ·  {citation}" if citation else cid
            qw_rows.append([
                ref,
                w.get("title", ""),
                w.get("description", ""),
                w.get("effort", ""),
                w.get("impact", ""),
            ])
        _build_table(
            doc,
            ["Control", "Title", "Description", "Effort", "Impact"],
            qw_rows,
            col_widths=[1.6, 1.6, 2.4, 0.7, 0.7],
        )
    else:
        _add_para(doc, "No quick wins listed.", size=11, color_hex=GRAY)

    if refine_meta:
        doc.add_paragraph()
        pass_count = refine_meta.get("pass_count", "?")
        history = refine_meta.get("history") or []
        final_status = ""
        if history:
            final_status = history[-1].get("status", "")
        footer_text = f"Validator passes: {pass_count} of 3"
        if final_status:
            footer_text = f"{footer_text}  ·  Final status: {final_status}"
        _add_para(doc, footer_text, size=9, color_hex=LGRAY,
                  align=WD_ALIGN_PARAGRAPH.RIGHT)

    doc.add_paragraph()
    _add_heading(doc, "Disclaimer", level=2, color_hex=LGRAY)
    _add_para(doc, DISCLAIMER_TEXT, size=10, color_hex=LGRAY)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def docx_to_pdf_bytes(docx_bytes: bytes) -> bytes | None:
    if not docx_bytes:
        return None
    soffice = shutil.which("soffice") or shutil.which("libreoffice")
    if not soffice:
        return None
    try:
        with tempfile.TemporaryDirectory() as tmp:
            src = os.path.join(tmp, "input.docx")
            with open(src, "wb") as f:
                f.write(docx_bytes)
            dash = "-" + "-"
            args = [
                soffice,
                dash + "headless",
                dash + "convert-to",
                "pdf",
                dash + "outdir",
                tmp,
                src,
            ]
            proc = subprocess.run(args, capture_output=True, timeout=60)
            if proc.returncode != 0:
                return None
            out_path = os.path.join(tmp, "input.pdf")
            if not os.path.exists(out_path):
                return None
            with open(out_path, "rb") as f:
                return f.read()
    except Exception:
        return None
