"""PDF export for HIPAA assessment reports."""
from fpdf import FPDF
from datetime import date
import io


class HIPAAReportPDF(FPDF):
    def __init__(self, org_name: str):
        super().__init__()
        self.org_name = org_name
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(99, 102, 241)  # Indigo
        self.cell(0, 8, f"HIPAA Readiness Assessment — {self.org_name}", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Generated {date.today().isoformat()}", align="R")
        self.ln(4)
        self.set_draw_color(99, 102, 241)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} — Confidential", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(99, 102, 241)
        self.ln(4)
        self.cell(0, 8, title, ln=True)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 6, text)
        self.ln(2)


def generate_assessment_pdf(
    org_context: dict,
    readiness: dict,
    controls: list[dict],
    baa_summary: dict,
    claude_analysis: dict = None,
) -> bytes:
    pdf = HIPAAReportPDF(org_context.get("org_name", "Organization"))
    pdf.add_page()

    # Executive summary
    pdf.section_title("Executive Summary")
    score = readiness.get("overall", 0)
    band = readiness.get("band_label", "Unknown")
    pdf.body_text(
        f"Overall HIPAA Readiness Score: {score:.1f}% — {band}\n"
        f"Assessment Date: {date.today().isoformat()}\n"
        f"Entity Type: {org_context.get('entity_type', 'N/A')}\n"
        f"SOC2 Status: {org_context.get('soc2_status', 'None')}\n"
        f"ePHI Systems: {', '.join(org_context.get('ephi_systems', []))}"
    )

    if claude_analysis:
        pdf.body_text(f"AI Analysis: {claude_analysis.get('gap_summary', '')}")
        pdf.body_text(f"Overall Risk Tier: {claude_analysis.get('overall_risk_tier', 'N/A')}")

    # Scores by category
    pdf.section_title("Readiness Scores by Safeguard Category")
    cat_scores = readiness.get("category_scores", {})
    for cat, score in cat_scores.items():
        pdf.body_text(f"  {cat}: {score:.1f}%")

    # Critical gaps
    critical = readiness.get("critical_gaps", [])
    if critical:
        pdf.section_title(f"Critical Gaps ({len(critical)} Required Controls at 0%)")
        ctrl_map = {c["id"]: c for c in controls}
        for gap in critical:
            c = ctrl_map.get(gap["control_id"], {})
            pdf.body_text(
                f"• {gap['control_id']} — {c.get('spec', '')} [{c.get('standard', '')}]\n"
                f"  Status: {gap['status']} | Notes: {gap.get('notes', 'N/A')}"
            )

    # BAA summary
    pdf.section_title("Business Associate Agreement Status")
    pdf.body_text(
        f"Total Business Associates: {baa_summary.get('total', 0)}\n"
        f"ePHI-sharing Vendors: {baa_summary.get('ephi_vendors', 0)}\n"
        f"Missing BAAs (CRITICAL): {baa_summary.get('missing_baas', 0)}\n"
        f"Expired BAAs (HIGH): {baa_summary.get('expired', 0)}\n"
        f"Expiring within 90 days: {baa_summary.get('expiring_90d', 0)}\n"
        f"BAA Compliance Rate: {baa_summary.get('compliance_rate', 0):.1f}%"
    )

    pdf.add_page()
    pdf.section_title("Disclaimer")
    pdf.body_text(
        "This report is generated by an automated readiness tool and does not constitute legal "
        "advice or a formal HIPAA audit. Organizations should engage a qualified HIPAA compliance "
        "professional to validate findings and develop a formal compliance program."
    )

    return bytes(pdf.output())
